### ISSUE TITLE
Configure repo settings for proper development workflow

### ISSUE THREAD

**Issue by ctmbl** [iScsc/wiresmash#7]
As @gbrivady already started to do, we should properly setup the repo to enable a good development workflow, this should be easily done thanks to the acquired experience from other iScsc projects.
  
Here is a list of the first things I can think of:
 - [x] #8
 - [x] branch protection policy
 - [x] 1 or 2 GitHub Team to differentiate dev from maintainers
 - [x] create a GitHub *Project* as [iScsc website](https://github.com/orgs/iScsc/projects/1)
 - [x] #9
 - [ ] a test set *(I think this has been slightly address by #2 but not entirely sure)* *(using `ctest`?)*
 - [x] GitHub Action to compile and run test *(being address by #6)*
 - [x] a good README.md *(in process in #2 )*, see #13 
 - [x] #10
 - [x] #12
 - [ ] *a git hook to lint the code* #14 
 - [x] *a first wiki*
 - [ ] *issues and PR templates*
 

*the last 3 points seems less urgent I agree*

And **the most important thing**: people interested in the project, but that part will be discussed in private to make a fine presentation to the iScsc members :+1: 

Let me know what you think of this list!

**Comment by gbrivady** [comment]
All very good points! I will address some of them later today; it would be nice if you could have a look at the readme in #2 - even if you don't have the time to review the entire code

**Comment by amtoine** [comment]
> All very good points! I will address some of them later today; it would be nice if you could have a look at the readme in #2 - even if you don't have the time to review the entire code
>
do not forget, when addressing a point above, to mention the issue or the PR in here :wink:

**Comment by gbrivady** [comment]
I have created #10, #9 and #8 to tackle some points and linked them in the todo list;

As for the wiki, it already existed before the issue [https://github.com/iScsc/wiresmash/wiki](url);

Will make a github project soon:tm: and mark it as done;

That leaves branch protection and Github teams

**Comment by ctmbl** [comment]
> it would be nice if you could have a look at the readme in https://github.com/iScsc/wiresmash/pull/2 - even if you don't have the time to review the entire code

I'll do it!

**Comment by gbrivady** [comment]
Also added an item for #12

**Comment by ctmbl** [comment]
the readme looks fine, could do better, but we always can do better so for the moment that seems fine to me! 
maybe just a simple Table of Content and placing incoming functionalities at the end, but that's details

**Comment by gbrivady** [comment]
> the readme looks fine, could do better, but we always can do better so for the moment that seems fine to me!

If it's good enough for now, I will just make a low priority issue with what you said to keep it in mind

**Comment by gbrivady** [comment]
Ticked the teams items, since @amtoine already adressed it, and we have maintainers/admins/and devs, should do the job for now.

I think we should remove the test item, not really a repo issue per-se and deserve a lot of discussion to define scope/goals/etc...

**Comment by amtoine** [comment]
@ctmbl 
hey :wave: 

i think the `main` branch is properly protected :+1:

**Comment by ctmbl** [comment]
then @gbrivady feel free to tick the appropriate task!
